# Generated by Django 3.2.11 on 2022-01-13 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_restaurant_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='close_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hour',
            name='open_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
