# Generated by Django 3.2.11 on 2022-01-13 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220113_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='day',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Hour',
        ),
    ]
